---
title: "randomizer"
output: html_document
---

```{r}
library(readxl)
#library(marginaleffects)
library(dplyr)
library(sandwich)   # for robust SEs
library(lmtest)     # for coeftest()
#library(tidyverse)
library(data.table)
```

Initial randomization has been run... move down to randomizer updater code.

```{r}
path <- "Experiment_Data .xlsx"
ingest_data <- read_excel(path, sheet = "Consolidated Data - Static")    # by name
init_data <- ingest_data %>%  filter(ingest_data$'Pre-Treatment Description' == "No")
init_data
```

```{r}
stigma_dogs <- as.data.table(init_data[init_data$"Breed Group"=="Stigma",])
stigma_dogs
nonstigma_dogs <- as.data.table(init_data[init_data$"Breed Group"=="Non-Stigma",])
nonstigma_dogs
```

```{r}

set.seed(1013)
stigma_dogs[, treatment := rbinom(.N, 1, 0.5)]
stigma_dogs

stigma_dogs %>%
  group_by(treatment) %>%
  summarise(count = n())

nonstigma_dogs[, treatment := rbinom(.N, 1, 0.5)]
nonstigma_dogs

nonstigma_dogs %>%
  group_by(treatment) %>%
  summarise(count = n())
```



```{r}
combined_dt <- rbind(stigma_dogs, nonstigma_dogs)
```

```{r}
write.csv(combined_dt, file = "InitialRandom_10_07_25.csv", row.names = FALSE)
```






********DO NOT USE***************
```{r}
# Create dog IDs
print(nrow(init_data %>%  filter(init_data$'Pre-Treatment Description' == "No")))
stigma_dogs <- init_data %>%
  filter(init_data$'Breed Group'=="Stigma", init_data$'Pre-Treatment Description' == "No")
stigma_dogs = stigma_dogs$Rescue_ID
length(stigma_dogs)
nonstigma_dogs <- init_data %>%
  filter(init_data$'Breed Group'=="Non-Stigma", init_data$'Pre-Treatment Description' == "No")
nonstigma_dogs = nonstigma_dogs$Rescue_ID
length(nonstigma_dogs)
```

```{r}
init_data %>%  filter(init_data$Rescue_ID == 'A0058282139')
```


```{r}
# Randomly assign 50% of each sex to treatment
stigma_treatment <- sample(male_dogs, size = floor(length(stigma_dogs) / 2))
length(stigma_treatment)
nonstigma_treatment <- sample(female_dogs, size = floor(length(nonstigma_dogs) / 2))
length(nonstigma_treatment)
```



```{r}
# Create a vector of treatment IDs
treatment_ids <- c(stigma_treatment, nonstigma_treatment)

length(treatment_ids)

# Assign Treatment = 1 if DogID is in treatment_ids, else 0
# init_data$Treatment <- ifelse(init_data$Rescue_ID %in% treatment_ids, 1, 0)
```

```{r}
#init_data
```

```{r}
write.csv(treatment_ids, file = "InitialRandom_10_07_25.csv", row.names = FALSE)
```


ALL ADDITIONAL RANDOMIZATIONS WILL BE DONE ON A BATCH/TWICE WEEKLY BASIS


```{r}
path <- "Experiment_Data.xlsx"
initial_data <- read_excel(path, sheet = "Randomize_10_18_25")
latest_data <- read_excel(path, sheet = "Consolidated Data - Static")
```


```{r}
initial_data
latest_data
```


```{r}
init_stigma_dogs <- as.data.table(initial_data[initial_data$"Breed Group"=="Stigma",])
stigma_dogs <- init_stigma_dogs[, c("Breed Group", "Rescue_ID", "Name - AdoptAPet","treatment")]
stigma_dogs
init_nonstigma_dogs <- as.data.table(initial_data[initial_data$"Breed Group"=="Non-Stigma",])
nonstigma_dogs <- init_nonstigma_dogs[, c("Breed Group", "Rescue_ID", "Name - AdoptAPet","treatment")]
nonstigma_dogs
init_latest_stigma <- as.data.table(latest_data[latest_data$"Breed Group"=="Stigma",])
latest_stigma_dogs <- init_latest_stigma[is.na(init_latest_stigma$`Initial T/C Find`), c("Breed Group", "Rescue_ID", "Name - AdoptAPet")]
#latest_stigma_dogs <- na.omit(latest_stigma_dogs)
latest_stigma_dogs
init_latest_nonstigma <- as.data.table(latest_data[latest_data$"Breed Group"=="Non-Stigma",])
latest_nonstigma_dogs <- init_latest_nonstigma[is.na(init_latest_nonstigma$`Initial T/C Find`), c("Breed Group", "Rescue_ID", "Name - AdoptAPet")]
#latest_nonstigma_dogs <- na.omit(latest_nonstigma_dogs)
latest_nonstigma_dogs 
```

```{r}
total_sitgma <- rbindlist(list(stigma_dogs,latest_stigma_dogs),fill = TRUE)
total_nonsitgma <- rbindlist(list(nonstigma_dogs,latest_nonstigma_dogs),fill = TRUE)
total_sitgma
total_nonsitgma
```



```{r}
set.seed(1013)
latest_stigma_dogs[, treatment := rbinom(.N, 1, 0.5)]
total_sitgma

latest_stigma_dogs %>%
  group_by(treatment) %>%
  summarise(count = n())

latest_nonstigma_dogs[, treatment := rbinom(.N, 1, 0.5)]
latest_nonstigma_dogs

latest_nonstigma_dogs %>%
  group_by(treatment) %>%
  summarise(count = n())
```


```{r}
total_sitgma <- rbindlist(list(stigma_dogs,latest_stigma_dogs),fill = TRUE)
total_nonsitgma <- rbindlist(list(nonstigma_dogs,latest_nonstigma_dogs),fill = TRUE)
total_sitgma
total_nonsitgma
```

```{r}
combined_dt <- rbind(total_sitgma, total_nonsitgma)
combined_dt
```

```{r}
write.csv(combined_dt, file = "Randomize_11_17_25.csv", row.names = FALSE)
```










